### PR TITLE
added missing french localisation

### PR DESCRIPTION
**Pull request by Gerokusu**
added and fixed some missing translations for the french users

### CODE REVIEW

**Comment by TheKrowi** [comment]
Thank you for translating some of the texts @Gerokusu but there is an Excel that contains all translations so I'm afraid I can merge this pull request. If you're interested in translating some more, hop on discord and I can explain you more. https://discord.gg/aNDmZ7hg

**Comment by TheKrowi** [comment]
Texts are added to Excel and merged into the dev branch.

**Comment by Gerokusu** [comment]
I wasn't aware of the process, I will hop soon to check this, thanks !

**Comment by TheKrowi** [comment]
No problem, I appreciate you helping out :)

**Pull request closed without merging**
